### ISSUE TITLE
post-install script failed, if PROXY_HOST set

### ISSUE THREAD

**Issue by makon2** [zhubanRuban/ConCygSys#1]
if PROXY_HOST set, the generated post-install.sh failed with error:
\cygwin\post-install.sh: line 5: syntax error near unexpected token `then'
The failure is the ";" in line 5 with echo:   the ";" terminate the command and then the "then" is unexpected.
Is "then" allone in the next line, then it works:
		echo if [[ $HOSTNAME == "%COMPUTERNAME%" ]]
		echo then
You can try in a interactiv shell:     echo message; then      it display the same error.
With kind regards

**Comment by 0zhu** [comment]
Thanks!
This fix is also available in [beta tree](https://github.com/zhubanRuban/ConCygSys/tree/beta) for now.
