### ISSUE TITLE
missing escape character for shell "$" / missing proxy setting in post-install.sh

### ISSUE THREAD

**Issue by makon2** [zhubanRuban/ConCygSys#2]
a) the generated script with "echo echo ... " needs a "\" (back-slash) to protecd the "$". otherwise the $ is missing in the script - with the result that the variable is empty at runtime.
b) during the install - the proxy setting is missing in the "post_install.sh".  in "pre_install it is set in the first lines. if the PC ( in my case win7) has no direct internet access, the "wget" in the post_install.sh fails - because no proxy is set. 

i have added the corrected script. the changes you see with "diff".
.. i cant upload the file -...sonething wrong.
i add diff:
```
394c395,396
<               echo if [[ $HOSTNAME == "%COMPUTERNAME%" ]]; then
---
>               echo if [[ $HOSTNAME == "%COMPUTERNAME%" ]]
>               echo then
522a525,531
>       if not "%PROXY_HOST%" == "" (
>               echo if [[ $HOSTNAME == "%COMPUTERNAME%" ]]
>               echo then
>               echo    export http_proxy=http://%PROXY_HOST%:%PROXY_PORT%
>               echo    export https_proxy=$http_proxy
>               echo fi
>       )
532c541,542
<               echo echo if [[ $HOSTNAME == "%COMPUTERNAME%" ]]; then
---
>               echo echo if [[ \$HOSTNAME == "%COMPUTERNAME%" ]]
>               echo echo then
534c544
<               echo echo       export https_proxy=$http_proxy
---
>               echo echo       export https_proxy=\$http_proxy
536,538c546,548
<               echo echo       export HTTP_PROXY=$http_proxy
<               echo echo       export HTTPS_PROXY=$http_proxy
<               echo echo       export NO_PROXY=$no_proxy
---
>               echo echo       export HTTP_PROXY=\$http_proxy
>               echo echo       export HTTPS_PROXY=\$http_proxy
>               echo echo       export NO_PROXY=\$no_proxy
```

**Comment by 0zhu** [comment]
Thank you for noticing and taking time to report this!
The fix is available in [beta tree](https://github.com/zhubanRuban/ConCygSys/tree/beta) for now.

I would appreciate if you could test this from your end as well (just to be sure):
- Download **`ConCygSys-installer.cmd`** from [this link](https://github.com/zhubanRuban/ConCygSys/raw/beta/ConCygSys-installer.cmd) *(right click > save link as)* to existing ConCygSys directory
- Launch **`ConCygSys-installer`**

**Comment by makon2** [comment]
i did it again on the same pc - and everything went fine !

thank you for creating this script - it is very nice !

last I forgot to mention that there are three bytes at the beginning of the file, which lead to an error message under windows 7 (which does not affect the function - only all commands are displayed):

0000000 357 273 277 @   e   c   h   o       o   f   f \r  \n  \r  \n

0000020   :   : C   o   n   C   y   g   S   y   s   :       C   y

0000040   g   w   i n       a   n   d       C   o   n   E   m   u

0000060   p   o   r t   a   b   l   e       i   n   s   t   a   l   l

0000100   e   r       h   t   t p   s   :   /   /   g   i   t   h   u

0000120   b   .   c o   m   /   z   h   u   b   a   n   R   u   b   a

0000140   n   /   C o   n   C   y   g   S   y   s  \r  \n   :   :

work-a-round: if you put the "@echo" in the second line, then an error already shows, but the "@echo off" works.

S:\Temp>ConCygSys-installer.cmd

S:\Temp>∩╗┐@echo off

'∩╗┐@echo' is not recognized as an internal or external command,

operable program or batch file.


*Betreff:* Fwd: [zhubanRuban/ConCygSys] missing escape character for shell "$" / missing proxy setting in post-install.sh (#2)




Anfang der weitergeleiteten E‑Mail:

    *Von:* zhubanRuban <notifications@github.com <mailto:notifications@github.com>>
    *Datum:* 25. Juni 2018 10:25:00 MESZ
    *An:* zhubanRuban/ConCygSys <ConCygSys@noreply.github.com <mailto:ConCygSys@noreply.github.com>>
      <author@noreply.github.com <mailto:author@noreply.github.com>>
    *Betreff:* *Re: [zhubanRuban/ConCygSys] missing escape character for shell "$" / missing proxy setting in post-install.sh (#2)*
    *Antwort an:* zhubanRuban/ConCygSys <reply@reply.github.com <mailto:reply@reply.github.com>>

    Thank you for noticing and taking time to report this!
    The fix is available in beta tree <https://github.com/zhubanRuban/ConCygSys/tree/beta> for now.

    I would appreciate if you could test this from your end as well (just to be sure):

      * Download |*ConCygSys-installer.cmd*| from this link <https://github.com/zhubanRuban/ConCygSys/raw/beta/ConCygSys-installer.cmd> /(right click > save link as)/ to existing ConCygSys directory
      * Launch |*ConCygSys-installer*|

**Comment by 0zhu** [comment]
It seems that the file was downloaded broken. I tried to run the installation / update multiple times on Windows 7 and 10 without any issue.
